///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String flutterGenPubspec = '.dart_tool/flutter_gen/pubspec.yaml';
  static const String genL10nAppLocalizations = '.dart_tool/flutter_gen/gen_l10n/app_localizations.dart';
  static const String genL10nAppLocalizationsAr = '.dart_tool/flutter_gen/gen_l10n/app_localizations_ar.dart';
  static const String genL10nAppLocalizationsEn = '.dart_tool/flutter_gen/gen_l10n/app_localizations_en.dart';
  static const String imagesBackground = 'assets/images/background.jpeg';
  static const String imagesIconCheck = 'assets/images/icon_check.png';
  static const String imagesIconList = 'assets/images/icon_list.png';
  static const String imagesIconSettings = 'assets/images/icon_settings.png';
  static const String imagesSplashTodo = 'assets/images/splash_todo.png';
  static const String imagesSplashTodoDark = 'assets/images/splash_todo_dark.png';
  static const String x8664App = '.dart_tool/flutter_build/afcda949abd57bc7148ce8e7fad311ba/x86_64/app.so';

}
